### ISSUE TITLE
After Effects exporter not working

### ISSUE THREAD

**Issue by JoeAllison** [facebookincubator/Keyframes#100]
The exporter in after effects isn't exporting a JSON file. The script panel says it's exporting but never finishes. No JSON file is exported, only a log file that's completely blank with no file size.

Can someone please help to confirm if there's an issue or if I've not set it up correctly.

Thanks

**Comment by leeyc09** [comment]
Scripts\Keyframes After Effects Scripts\lib\keyframes\AECompToKeyframesAnimation.js

remove these line :
```
keyPath.unshift(comp&&comp.parentFolder$name);
console.warn('UNSUPPORTED: %s',keyPath.join(' → '));```

you will work fine..

**Comment by JoeAllison** [comment]
Thanks for getting back to me.

I've removed those 2lines, but It's still not worked unfortunately.

When I try the command line export and type 'keyframes-cli' it says the command is not found.

**Comment by leeyc09** [comment]
did you allow Scripts To Write Files And Access Network option?

**Comment by JoeAllison** [comment]
Yea I think I have everything set up correctly with that. Here's a screenshot of the after effects settings:

![image](https://cloud.githubusercontent.com/assets/3280156/21678704/0e169bba-d338-11e6-821a-f18087abeb15.png)

**Comment by Nabeel-khalid** [comment]
Are you on AE 2017?

**Comment by JoeAllison** [comment]
Yea I was originally on 2015 having the issues, but I upgraded to 2017 yesterday to see if that would help.

**Comment by Nabeel-khalid** [comment]
Yeah I think it's a issue with AE export [See this](https://github.com/facebookincubator/Keyframes/issues/65)

**Comment by leeyc09** [comment]
I can use both 2015 and 2017

**Comment by leandrinux** [comment]
Check if you have Node installed in your computer. You can get error messages if you try running the script from the console instead of using the AE menu option.

**Comment by leandrinux** [comment]
It looks like it can't find the "package.json" file. You should run those commands inside the `scripts` directory included in the repo.

**Comment by JoeAllison** [comment]
I'm still not able to get it to work unfortunately. I also tried updating to Sierra as someone said that helped for them, but it's still holding on the export and not generating the files. No luck with the Command line method either :(

**Comment by maxshelest** [comment]
Before exporting, save the AE project
<img width="275" alt="2017-01-09 13 39 01" src="https://cloud.githubusercontent.com/assets/23740080/21763881/3a7cb1a8-d671-11e6-9fb6-bab262b20c76.png">

**Comment by JoeAllison** [comment]
Thanks, the json file is now being exported, but it's not playable. I've been using the keyframes player app which works with pre-exported examples I've downloaded, but not the json files that being exported by the ae script. It's exporting a .kf.json and a .json file and .log file.

I also tried it on a simple IOS app a friend created for me to play them on which again works with downloaded examples, but not with the exported files.

**Comment by lozzle** [comment]
Hi @JoeAllison-- are you files formatted properly, according to some of the guidelines set here? https://github.com/facebookincubator/Keyframes/blob/master/docs/AfterEffectsGuideline.md

Otherwise, if you could send over an example comp or the exported file, it would help greatly in identifying what exactly is going wrong.

**Comment by JoeAllison** [comment]
Hey thanks, I'm using After Effects 2017, does it only work with 2015? Otherwise, it's a very simple comp to test with, and i'm pretty sure it all complies with the rules in the guidelines. I've attached a zip of the AE file and the export
[keyframes_test.zip](https://github.com/facebookincubator/Keyframes/files/695604/keyframes_test.zip)

**Comment by maxshelest** [comment]
Draw points ( béziers )
<img width="1187" alt="2017-01-11 15 53 08" src="https://cloud.githubusercontent.com/assets/23740080/21849372/74a0daa2-d816-11e6-8126-1cb2386cae5b.png">

**Comment by cadicetienne** [comment]
FYI One of our art director experienced the "never ending" exporter issue, even with a saved project.
When using the cli we found out there was a JS error when trying to write logs. (The error was when performing the new Date().toISOString()) in Extended script FB Keyframes Exporter.jsx, line 33).

--> the JS error was somthing like "can't apply prototype function .toISOString to an infinite date". No clue why the new Date() isn't working properly on his mac (most of us doesn't have any problem).

Removing the statement solved the problem and he can now perform the export properly.

Maybe you guys are experiencing the same issue ?

**Comment by subtleGradient** [comment]
There's a fix for that and a bunch of stuff in review. I'll try to land it
today or tomorrow

**Comment by subtleGradient** [comment]
Sorry for all the instability until now.
Try the latest version here: https://github.com/facebookincubator/Keyframes/releases/tag/previewer-v1
It fixes a bunch of little bugs and has better error handling. It also includes a Previewer for Android.

Let me know if this still gives you any problems.

**Comment by JoeAllison** [comment]
Hey, thanks for the updated version. I've tried it out, unfortunately it's still not working. I'm not sure why this could be. The exporter is exporting the kf.json files, but I'm not able to run them. I have the extendscript toolkit installed. I've tried the command line tool, but when I run it says 'command not found'.

Mac os sierra v10.12
AE 2017 14.0.1.5

I've attached the source files if you're able to give any advice at all I'd really appreciate it. I'm dying to get this working!


________________________________

**Comment by cadicetienne** [comment]
I tried to run a demo with your file. You're right nothing appears to the screen but I think it comes more from your artboard / AE config / scene than the exporting script or the mobile framework.

At least, the animation duration is working properly 'cause I got the event when the animation finishes. I think you may be drawing your items out of the viewbox. Try and start designing your animation from the artboard of the sample keyframe logo ?

**Comment by JoeAllison** [comment]
Amazing, thanks for looking into it. It's working now as long I start the animation from the logo example file. I've had a few issues with the positioning of shapes, and yea I think they were appearing off the artboard for some reason like you said. I'll practice it further.

Thanks again for your help,
- Joe


________________________________

**Comment by subtleGradient** [comment]
My pleasure!
The changes have landed in master now.
I recommend using the Previewer often. You'll catch unsupported features and other issues faster that way. Sorry it isn't faster :(
