### ISSUE TITLE
Pod name is `keyframes` instead of `Keyframes`

### ISSUE THREAD

**Issue by sampsakuronen** [facebookincubator/Keyframes#120]
Readme states that pod name is `Keyframes`. This seems to be case sensitive though, as a specification with that name can't be found. By using `keyframes` (lower cased) the pod can be installed.

In `Podfile`: `pod 'Keyframes'`

```
pod install
Analyzing dependencies
[!] Unable to find a specification for `Keyframes`
```

And then:`Podfile` - `pod 'keyframes'`

```
pod install
...
Installing keyframes (1.0.0)
```

**Comment by ptomasroos** [comment]
This is now fixed in master @sampsakuronen. Please close
