### ISSUE TITLE
Any updates on the new release date?

### ISSUE THREAD

**Issue by jadidian** [facebookincubator/Keyframes#125]
Hi, thanks for the awesome project.
I was wondering if you're planning to publish a new release anytime soon, including opacity, seek & resume functionality for Android.
I wanted to use the [react-native-facebook-keyframes](https://github.com/underscopeio/react-native-facebook-keyframes) in a react native project, is it possible to compile the `keyframes.jar` from this repo including the latest commits? I'm not a Java / Android developer and I'd appreciate if someone explains how to do this.

**Comment by LazyChild** [comment]
https://github.com/facebookincubator/Keyframes/releases/download/v1.1.0/keyframes-1.1.0.jar
