### ISSUE TITLE
[iOS] animationDidStopBlock called twice

### ISSUE THREAD

**Issue by sanatory** [facebookincubator/Keyframes#126]
animationDidStopBlock is called twice. and the first time is immediately after the start

**Comment by sanatory** [comment]
sorry, just don't call startAnimation before you add sublayer, or subview

**Comment by Ekhoo** [comment]
Any news ?

**Comment by LazyChild** [comment]
@Ekhoo that's how core animation handles this callback. But the finished parameter should be NO for the first call?

**Comment by Ekhoo** [comment]
Ok in your last cocapods release, we haven't the `finished` parameter. Is it possible to make a new release with the callback parameter ?

**Comment by LazyChild** [comment]
@Ekhoo updated Cocoapod to 1.1.0

**Comment by Ekhoo** [comment]
Thank you :)
