### ISSUE TITLE
Support React Native

### ISSUE THREAD

**Issue by lucasbento** [facebookincubator/Keyframes#23]
This is an awesome library, is there a current path to use it with React Native?

Thanks.

**Comment by lozzle** [comment]
Unfortunately, there is not a way to use it with React Native at the moment.

**Comment by subtleGradient** [comment]
We have experimented with an additional implementation based off of react-art which would support web and React Native. It's still on our long long term wishlist.

In the meantime, you should be able to wrap the iOS and Android native implementations and expose them to React Native in the usual way.

**Comment by browniefed** [comment]
Any chance you could share the react-art experiment?
I'd love to take a look at it and work on it, if not I'll just give it a go from scratch.

**Comment by browniefed** [comment]
@subtleGradient question was targeted at you
