### ISSUE TITLE
Release as open source

### ISSUE THREAD

**Issue by bootstraponline** [facebookincubator/Keyframes#24]
As discussed on [Hacker News](https://news.ycombinator.com/item?id=13015035), `Keyframes` isn't meeting the [Open Source Definition](https://opensource.org/osd) due to the unusual custom license.

 > provided Your Software does not consist solely of the Software;

Facebook has a history of writing custom proprietary licenses, [for example react-native](https://github.com/facebook/react-native/blob/master/Examples/TicTacToe/TicTacToeApp.js). Is there any hope of Facebook making a legitimate open source release of Keyframes?

**Comment by jjt** [comment]
I've reproduced Keyframes and am distributing here: https://github.com/jjt/Keyframes

**Comment by jancona** [comment]
I find clause 3 of the license bad also, since it says that you can only use changes internally. Taken together, I read the license as saying that you may only release unmodified copies of the code and only as part of a larger project.

**Comment by caabernathy** [comment]
The Keyframes license is being fixed. Thanks!

**Comment by lozzle** [comment]
https://github.com/facebookincubator/Keyframes/pull/32
