### ISSUE TITLE
Provide sample JSON files

### ISSUE THREAD

**Issue by Odaym** [facebookincubator/Keyframes#27]
I wasn't able to find them (correct me if I'm wrong) but it would be nice to have a couple of sample JSON files to be able to write up a quick test and check things out without needing to install After Effects and whatnot, bandwidth doesn't help me. Thanks

**Comment by lozzle** [comment]
We have one in the sample apps in each directory: https://github.com/facebookincubator/Keyframes/tree/master/android/keyframes-sample/src/main/assets

**Comment by Odaym** [comment]
oh, missed it, thanks!
