### ISSUE TITLE
support react native

### ISSUE THREAD

**Issue by chirag04** [facebookincubator/Keyframes#30]
Seems like all the pieces for using react native is already there. just need to put together as a module.

**Comment by subtleGradient** [comment]
I'd love to have this.

**Comment by James-Parsons** [comment]
Honestly, I wish FB would work to port more of their stuff to RN

**Comment by hansemannn** [comment]
Maybe try the Titanium one? 😊 https://twitter.com/hansemannnn/status/801633195699634177

**Comment by cupofjoakim** [comment]
I'd say this is crucial!

**Comment by triniwiz** [comment]
Even NativeScript https://twitter.com/NativeScript/status/801691221534056448

**Comment by James-Parsons** [comment]
@triniwiz I'm waiting for the great war between {N} and React Native 😉.

**Comment by jpgarcia** [comment]
Hey Guys, 

We just published a `React Native` wrapper with **Android** and **iOS** support. (also related to #23)

https://github.com/underscopeio/react-native-facebook-keyframes

Let us know if you find any issues. Hope it helps!

**Comment by m1ga** [comment]
@hansemannn @jpgarcia I've added a list of existing frameworks solutions at https://github.com/facebookincubator/Keyframes/pull/81 
Please check the author field if that's fine for you
