### ISSUE TITLE
Add swift demo

### ISSUE THREAD

**Issue by hansemannn** [facebookincubator/Keyframes#36]
Hey guys,

anyone interested in a Swift 3 port? I'd port it, but not if someone already works on it. Thx!

P.S.: Great library! 🚀

**Comment by lozzle** [comment]
Hi, @hansemannn!  Thanks for your interest 😄

If you're interested in making a Swift port, you are more than welcome to!  We have no plans at the moment for porting the iOS renderer to Swift.

**Comment by hansemannn** [comment]
Cool! Added the demo in #37.
