### ISSUE TITLE
Runtime error on iOS

### ISSUE THREAD

**Issue by revolter** [facebookincubator/Keyframes#40]
When trying to run the sample app on an iOS device, I get this error message:

> dyld: Library not loaded: @rpath/keyframes.framework/keyframes
>  Referenced from: /var/containers/Bundle/Application/53D31992-2E40-4E7A-82DB-B0AB58B46AFE/keyframes-sample-ios.app/keyframes-sample-ios
>  Reason: image not found

**Comment by hansemannn** [comment]
@revolter Did you try to run it as an embedded framework (`General` / `Embedded Binaries`)?

**Comment by revolter** [comment]
Could you tell me how to do that? I was expecting the sample app is just a stand alone app that showcases the library.
