### ISSUE TITLE
Animation not showing on iOS & Android

### ISSUE THREAD

**Issue by daveobrien-EB** [facebookincubator/Keyframes#41]
I installed and ran the AE script as instructed but when I try and my exported JSON file in the Xcode  example project or Android Studio nothing shows up. It's a very simple rotation example. 
Am I missing something here? 

using AE version 14.0.1.5

{
  "formatVersion": "1.0",
  "name": "COMP",
  "key": 1,
  "frame_rate": 24,
  "animation_frame_count": 24,
  "canvas_size": [
    600,
    600
  ],
  "features": [
    {
      "name": "Shape Layer 1",
      "feature_animations": [
        {
          "property": "ANCHOR_POINT",
          "key_values": [
            {
              "start_frame": 0,
              "data": [
                13.3359375,
                33.3359375
              ]
            }
          ],
          "timing_curves": [
            
          ]
        },
        {
          "property": "X_POSITION",
          "key_values": [
            {
              "start_frame": 0,
              "data": [
                300
              ]
            }
          ],
          "timing_curves": [
            
          ]
        },
        {
          "property": "Y_POSITION",
          "key_values": [
            {
              "start_frame": 0,
              "data": [
                300
              ]
            }
          ],
          "timing_curves": [
            
          ]
        },
        {
          "property": "ROTATION",
          "key_values": [
            {
              "start_frame": 0,
              "data": [
                0
              ]
            },
            {
              "start_frame": 24,
              "data": [
                180
              ]
            }
          ],
          "timing_curves": [
            [
              [
                0.33333333,
                0
              ],
              [
                0.66666667,
                1
              ]
            ]
          ]
        }
      ],
      "stroke_line_cap": "butt",
      "fill_color": "#ff5f90df",
      "stroke_color": "#ffffffff",
      "stroke_width": 0
    }
  ],
  "animation_groups": [
    
  ]
}

**Comment by lozzle** [comment]
There doesn't seem to be any path information being exported here-- did your comp follow the format shown here? https://github.com/facebookincubator/Keyframes/blob/master/docs/AfterEffectsGuideline.md

Currently our exporter doesn't support shapes like Rectangle or Ellipse, but require a path, so that may also be the issue.  Adding Rectangle/Ellipse support is something we have on our radar, though!

**Comment by daveobrien-EB** [comment]
Ah yes, not supporting the Rect and Ellipse is most likely it then.
