### ISSUE TITLE
Dynamic animations

### ISSUE THREAD

**Issue by carobeta** [facebookincubator/Keyframes#42]
It's possible to create animations and add them into diferente images? To make it more dynamic

**Comment by lozzle** [comment]
Do you mean transforming other elements via transforms defined in AE?

We have something very experimental to map bitmaps into matrices in the Android lib, and I'm pretty sure in the iOS one as well.  It shouldn't be too much extra work to map these to arbitrary elements.  It's currently not supported out of the box though.

**Comment by carobeta** [comment]
No, what I want it's change the image source of an animation. 

Because, your recommendation it's good but not allow the animation to be applied on the image.

**Comment by carobeta** [comment]
Thanks! KFVectorBitmapFeatureLayer is the layer that I need!
