### ISSUE TITLE
Gradient Ramp not working

### ISSUE THREAD

**Issue by pinkred** [facebookincubator/Keyframes#44]
Hello.

used gradient ramp but json data not exist "effects", "gradient".
I looked up the source in github, Related code did not exist.
 
I want Gradient Ramp animation.

Thank you.

**Comment by markjeschke** [comment]
@pinkred, I couldn't get the gradient ramp to export in the JSON either, despite that it renders properly within the After Effects environment.

**Comment by lozzle** [comment]
Hi @pinkred, gradient ramp is something that is on our roadmap of features to add.  it's not currently supported in the library

**Comment by markjeschke** [comment]
@lozzle, you may want to remove the experimental gradient ramp effect section instructions and screenshots until the enhancement gets added: 

[https://github.com/facebookincubator/Keyframes/blob/master/docs/AfterEffectsGuideline.md#gradient-experimental-feature](
https://github.com/facebookincubator/Keyframes/blob/master/docs/AfterEffectsGuideline.md#gradient-experimental-feature)

Including this gradient ramp effect in the After Effects Guideline ReadMe makes it seem like it's something that we can currently implement and test, but is perhaps still a work in progress.

**Comment by lozzle** [comment]
@markjeschke Sorry about not having more clarity!  I'll change this to reflect that it's a WIP.  On a side note, we're putting together some resources to better communicate what is fully supported vs what is on our roadmap / under work, as well as missing features and other work we'd like to tackle.

**Comment by juliensechaud** [comment]
@lozzle I tried to use LINEAR gradient which seems to be supported (cf. https://github.com/facebookincubator/Keyframes/blob/master/docs/AfterEffectsGuideline.md#gradient-experimental-feature) following the guidelines.
But after exporting there is not any effects or gradients in the JSON.
Any idea ? Is this feature really supported ?
Thanks
