### ISSUE TITLE
black background in Lollipop devices

### ISSUE THREAD

**Issue by imlunacat** [facebookincubator/Keyframes#47]
Hello,
  I clone the repo and play it on Android devices. I got a ```ImageView``` with black background like:

> ( Nexus 5X, Android 7.1.1, LAYER_TYPE_SOFTWARE )

![nexus_5x_soft_1_3rd](https://cloud.githubusercontent.com/assets/2828387/20737633/ea228108-b6e8-11e6-8072-68b73ca51ba6.png) 

  If I remove ``` imageView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);```, the background of ```ImageView``` becom transparent as excepted.

> ( Nexus 5X, Android 7.1.1, LAYER_TYPE_NONE )

![nexus_5x_none_1_3rd](https://cloud.githubusercontent.com/assets/2828387/20737937/b3e1c57a-b6ea-11e6-826d-3b340cb84a04.png)

  Same situation happens in other devices
> ( Galaxy S4, Android 5.0.1, LAYER_TYPE_SOFTWARE )

![samsung_soft_1_3rd](https://cloud.githubusercontent.com/assets/2828387/20738028/4c7459c4-b6eb-11e6-9c61-3ba818a40230.png)

> ( Galaxy S4, Android 5.0.1, LAYER_TYPE_NONE )

![samsung_none_1_3rd](https://cloud.githubusercontent.com/assets/2828387/20738024/472d4624-b6eb-11e6-9175-02d821bac6c0.png)

But in 4.4, LAYER_TYPE_SOFTWARE works.

> ( Android Emulator, Android 4.4
![emu_api_19_soft_half](https://cloud.githubusercontent.com/assets/2828387/20738084/bd2f8a4e-b6eb-11e6-883d-17653eaccda3.png)

  Should I close LAYER_TYPE_SOFTWARE in post-Lollipop devices?

**Comment by lozzle** [comment]
Hmm, I haven't seen this issue in any post-Lollipop devices of mine, and I hadn't seen reports of it in the wild either.  Are all your screenshots emulator or actual devices?  Running stock Android?

From my testing, software layer improves framerate a bit, but if it's causing issues, hardware layer can be a workaround.

**Comment by eboudrant** [comment]
I also have black background issue when using a Google Pixel running Android 7.1

**Comment by imlunacat** [comment]
Hello @lozzle, black background issue happens in real-device (Nexus 5X and Galaxy S4)

**Comment by vcalvello** [comment]
Hey guys! This is not a bug. Just set the alpha of the ImageView. 
`imageView.setImageAlpha(0)`
