### ISSUE TITLE
Script never ends

### ISSUE THREAD

**Issue by carobeta** [facebookincubator/Keyframes#50]
I have an After Effects project, when I'm going to execute the script, this never ends, only display 'exporting'.

**Comment by markjeschke** [comment]
@carobeta, is this a new After Effects project? Did you check the settings for Enabling scripts to write to disk? Please see:

https://github.com/facebookincubator/Keyframes/issues/28#issuecomment-263590844

**Comment by carobeta** [comment]
Thanks @markjeschke !!! I only need to save the After Effects project as a new copy!

**Comment by markjeschke** [comment]
You're welcome @carobeta. I just figured this out, yesterday. It is certainly not an obvious fix.
