### ISSUE TITLE
Masks? 

### ISSUE THREAD

**Issue by daveobrien-EB** [facebookincubator/Keyframes#52]
Maybe Im not doing it correctly, but is there a specific way to set up masks for it to be read properly by Keyframes? I've tried the traditional pen/shape mask and also the track matte. 
From looking at the Reactions animations it would seem like masks were used..  so was curious if there was support for this.

**Comment by lozzle** [comment]
Hey, Dave!

We are actually working on support for using track mattes for masking right now.  On the Android side, there's this branch I've been meaning to merge in that includes a few of these new features (masking commit here: https://github.com/facebookincubator/Keyframes/commit/4eb507941eb46a39bf74e5331e8873455ed6fa0a).

**Comment by daveobrien-EB** [comment]
@lozzle Good to know! thanks for the information

**Comment by daveobrien-EB** [comment]
Still having some masking issues even on the 'new android features' branch. Mask is working fine in AE between two shape layers, one with an Alpha Matte, masking the other but when I build in Android Studio the masking is not recognized.
