### ISSUE TITLE
new-android-features branch not support gradient animation

### ISSUE THREAD

**Issue by pinkred** [facebookincubator/Keyframes#53]
Hello.

I used gradient animation in master branch, but new-android-features don't support.
I compared two branch.

KeyFramedObject Class found problem.

master source has a variable "mInterpolators".

  public KeyFramedObject(List<T> objects, float[][][] timingCurves) {
    .....
     mInterpolators = KeyFrameAnimationHelper.buildInterpolatorList(timingCurves);
  }

but other branch source move updateWithFrameRate method.

 KeyFramedGradient not call updateWithFrameRate. So don't animation;

I modified my source. 

KeyframesDrawable class - prepareShadersForFeature method.

```
for (int i = 0; i < precision; i++) {
        progress = i / (float) (precision) * numFrames;

       // --> insert code
        gradient.getStartGradient().updateWithFrameRate(frameRate);
        gradient.getEndGradient().updateWithFrameRate(frameRate);
     // <-- 

        gradient.getStartGradient().apply(progress, colorPair);
        gradient.getEndGradient().apply(progress, colorPair);
        mCachedShaders[i] = new LinearGradient(
                0,
                0,
                0,
                mKFImage.getCanvasSize()[1],
                colorPair.getStartColor(),
                colorPair.getEndColor(),
                Shader.TileMode.CLAMP);
```

Thank you.

**Comment by rohandhruva** [comment]
@pinkred , can verify if pr #54 fixes the issue? It's the same fix as you have (thanks!), but applied at a different place in the flow.

**Comment by rohandhruva** [comment]
Closing, please re-open if the issue persists.
