### ISSUE TITLE
Play Animation without repeating in iOS

### ISSUE THREAD

**Issue by streamside7** [facebookincubator/Keyframes#59]
Thank you for this wonderful library. It's exactly what I need for an upcoming project. Great job! This definitely something I'd like to contribute to.

I'm just digging into the code right now, but I noticed in iOS, there is no equivalent to Android's stopAnimationAtLoopEnd so that the animation could only be played once. I've tried setRepeatCount (setting it both before and after starting the animation), and it still repeats. 

Is there a simple way to play an animation just one iteration in iOS? Thanks!

**Comment by streamside7** [comment]
I will answer my own question here: setRepeatCount does work; it just needed to be called before addSublayer is called (which makes sense now). Again, awesome job!

**Comment by lozzle** [comment]
thanks, @streamside7 glad you like the library!

in the future, we plan to consolidate our APIs on android vs ios so they match more closely, which should reduce the number of these types of issues 😄
