### ISSUE TITLE
Add resume and seek support on Android

### ISSUE THREAD

**Issue by vcalvello** [facebookincubator/Keyframes#60]

**Comment by lozzle** [comment]
seeking is somewhat supported via #setFrameProgress on KeyframesDrawable

**Comment by vcalvello** [comment]
Yup, but needs to call `invalidateSelf` in order to redraw. Also the progress value takes a value between 0 to 100 instead of 0 to 1.

I've just sent a PR adding a `seekToProgress` and `pauseAnimation/resumeAnimation` to feature parity with iOS version.
