### ISSUE TITLE
In Android 6.0 KeyframesDrawable background transparent is lose

### ISSUE THREAD

**Issue by mingming-killer** [facebookincubator/Keyframes#63]
![device-2016-12-09-144241](https://cloud.githubusercontent.com/assets/1267799/21040181/43011960-be1e-11e6-977f-23f1e4f22b4a.png)
![device-2016-12-09-144411](https://cloud.githubusercontent.com/assets/1267799/21040182/431d0238-be1e-11e6-956b-ab73013d1e09.png)

first screen shot is in nexus 6p running with android 7.0. I try to run in nexus 5x with android 6.0, background is also black.

2nd screen shot is running with android 4.4. I just use sample_file.json which in keyframes sample. and the keyframes sample is same result.

**Comment by vcalvello** [comment]
Hey @mingming-killer! Just set the alpha of the ImageView to 0.
 `imageView.setImageAlpha(0)`

**Comment by mingming-killer** [comment]
@vcalvello  It's work ... thanks.

**Comment by ursusursus** [comment]
Turning off the software rendering works as well?
