### ISSUE TITLE
After Effects Not Exporting

### ISSUE THREAD

**Issue by scurrey** [facebookincubator/Keyframes#65]
Adobe After Effects CC 2017 (UpToDate)

Installed Scripts
Turned on "Allow Scripts to write files"
Open File
Open Comp that I want to export only.
Run Script
See Export Dialog
Click Export
See "Exporting..."
Writes Blank Log File
Activity Manager - AE CPU usage is at 1.6%

Nothing else happens even leaving AE open overnight.

How can I get the script to work? I am a iOS dev and would love to use this in our pipeline.

**Comment by lozzle** [comment]
this is being tracked here:
https://github.com/facebookincubator/Keyframes/issues/28

**Comment by JoeAllison** [comment]
I'm still not able to get it to work unfortunately. I also tried updating to Sierra as someone said that helped for them, but it's still holding on the export and not generating the files. No luck with the Command line method either :(

**Comment by subtleGradient** [comment]
Sorry for all the trouble. I have a newer version of the exporter that
works a lot better and has way better error handling for when it does
break. I'll try to get it up here early next week.

Sorry for the delay 😰

**Comment by JoeAllison** [comment]
Thanks, The json files are now being exported, but aren't playable. I've been using the keyframes player app https://github.com/insidegui/KeyframesPlayer which works with pre-exported examples I've downloaded, but not the json files that being exported by the ae script. It's exporting a .kf.json and a .json file and .log file.

I also tried it on a simple IOS app a friend created for me to play them on which again works with downloaded examples, but not with the exported files.

**Comment by JoeAllison** [comment]
Hey, I'm still not able to use it. The exporter is exporting, but the code isn't playing anything. Here's a zip of what the exporter is generating with the source file. Is this working as it should be? 
[keyframe_test_v2.zip](https://github.com/facebookincubator/Keyframes/files/698984/keyframe_test_v2.zip)

**Comment by subtleGradient** [comment]
Sorry for all the instability until now.
Try the latest version here: https://github.com/facebookincubator/Keyframes/releases/tag/previewer-v1
It fixes a bunch of little bugs and has better error handling. It also includes a Previewer for Android.

Also, try using the sample project to sanity check that everything is working end to end.
The exporter only supports a subset of After Effects features right now, so there's a chance you're running into something that isn't supported yet.

**Comment by subtleGradient** [comment]
The changes have landed in master now.
