### ISSUE TITLE
Buildtime Warnings in framework?

### ISSUE THREAD

**Issue by markjeschke** [facebookincubator/Keyframes#73]
Are the following warnings anything to be concerned about?

* Warning: no umbrella header found for target 'keyframes', module map will not be generated
* Method override for the designated initializer of the superclass '-initWithFrame:' not found

<img width="323" alt="keyframes-framework-warnings" src="https://cloud.githubusercontent.com/assets/1577928/21281884/3054ea62-c3a5-11e6-8912-d29953b833d1.png">

Thanks,
Mark

**Comment by insidegui** [comment]
Nothing to worry about. The first one should be fixed with the new version because they added umbrella headers to the framework. The other two are not important, although they should probably be fixed by adding the specified overrides just to silence the compiler =]

**Comment by markjeschke** [comment]
Thank you for your quick response, @insidegui I appreciate your time and help. 

Take care,
Mark
