### ISSUE TITLE
How are these heart particles emitted?

### ISSUE THREAD

**Issue by markjeschke** [facebookincubator/Keyframes#74]
**Help Wanted:** 

If the team is willing to answer, are these heart particles in the animation example below, exported as a self-contained After Effects animation? Or, are the KFVectorLayers dynamically animated via something like SpriteKit or SceneKit particles?

Thanks in advance!

Take care,
Mark

<img src="https://scontent-sjc2-1.xx.fbcdn.net/t39.2365-6/15163977_298177397242602_5682248149289140224_n.gif" />

**Comment by LazyChild** [comment]
Hi @markjeschke,
it is self-contained After Effects animation.

**Comment by markjeschke** [comment]
Thank you for your response, @LazyChild. I appreciate it.
