### ISSUE TITLE
Shape exceeding comp bounds on iOs & Android

### ISSUE THREAD

**Issue by daveobrien-EB** [facebookincubator/Keyframes#76]
I have a comp which includes a circular shape layer that expands to a size that exceeds the bounds of the comp. It looks fine in AE but on device it doesnt seem to clip to the comp size.

**Comment by LazyChild** [comment]
@daveobrien-EB on iOS you can set `masksToBounds` to clip

**Comment by daveobrien-EB** [comment]
@LazyChild That works for now. Would be great to have this on both platforms by default in the future. Makes sense to respect the intension of the AE comp sizes. Thanks guys.
