### ISSUE TITLE
More (advanced) JSON example files

### ISSUE THREAD

**Issue by m1ga** [facebookincubator/Keyframes#80]
Are there any examples beside the keyframes logo JSON to try out? E.g. the emoticons?

I don't have access to AFX to create files but I would like to test more files on Android (I'm creating an Android module for Appcelerator Titanium: https://github.com/m1ga/ti.keyframes to support Keyframes) to see if everything is running fine.

**Comment by thewoodpecker** [comment]
@m1ga I created a few animated emoji and they worked well on iOS. The JSON files are here - https://www.dropbox.com/s/8cyy15gdc7s6gtu/smileys.zip?dl=0

Not sure if this is what you're after but I hope it helps.

![emoji-prediction](https://cloud.githubusercontent.com/assets/24732448/21471248/e9ea8d34-caa2-11e6-8f16-3527e1cbf11a.gif)

**Comment by m1ga** [comment]
@thewoodpecker thanks a lot 👍 Exactly what I was looking for. Running nice and smoothly!

Now I have to see if I can parse the canvas_size correctly to make it use this if you don't set a height/width in the framework.

A resource for free/paid animations would be fine if Keyframes gets used by a lot of people

**Comment by lozzle** [comment]
@thewoodpecker this is awesome!  i'm working on throwing together a github io page, and currently just have the keyframes logo as a sample resource.  do you mind if i throw this in that list as well?

https://facebookincubator.github.io/Keyframes/docs/sample-files

**Comment by Audiobrad** [comment]
Has anyone been able to get a json file to work accurately that doesn't have a 1:1 canvas size?

Everything we have tested at a different aspect ratio is squished and only renders correct when the x & y are the same value

**Comment by m1ga** [comment]
@Audiobrad the file @thewoodpecker posted is 148x54 and looking fine:
![gif](http://migaweb.de/keyframes2.gif)
(sorry for the low quality)
But I've set the ImageView size to exactly that size. Did you mean x and y have the same value as x and y of the source file or did you mean x == y ?

**Comment by lozzle** [comment]
Hi @Audiobrad, are you still having issues with x/y canvas scaling?  We've had some problems in the past on Android due to the way scaling is done in some comps, but I think we've addressed most of them.  If you have a comp or exported file that shows the issues we can take a look at, we might be able to help debug it.

**Comment by hansemannn** [comment]
Hey guys! I created [keyframes-collection](https://github.com/hansemannn/keyframes-collection) to collect useful keyframes :-) @lozzle Do we want this to be included in the readme as well?

**Comment by lozzle** [comment]
Yep @hansemannn, I can refer to this in the github.io!  We maybe could consolidate the two lists, since the github.io page is open for PR also.

**Comment by Audiobrad** [comment]
@lozzle @m1ga thanks for the replies. it sounds like the issues we were having were on our end and based on the container that was created for the animation.

**Comment by lozzle** [comment]
Closing this out, we should move any more advanced examples to the github io: https://facebookincubator.github.io/Keyframes/docs/sample-files
