### ISSUE TITLE
Colour blending modes like 'Multiply'

### ISSUE THREAD

**Issue by thewoodpecker** [facebookincubator/Keyframes#85]
Is there currently a way to use colour blending modes like multiply, overlay, etc? It doesn't seem to work when testing on iOS. 

This would be a great addition. Cheers!

![screen-shot-2016-12-30-at-17 58 13](https://cloud.githubusercontent.com/assets/24732448/21570020/0d4c9a68-ceba-11e6-95c5-570175284d93.jpg)

**Comment by lozzle** [comment]
yeah we don't support blend mode between different layers since we render things back in real time.  it's similar to why we're only planning on supporting masking via track matte for the near future (only requires interaction with one shape layer rather than all layers underneath)
