### ISSUE TITLE
Does the AfterEffects script work with CS6?

### ISSUE THREAD

**Issue by yozef** [facebookincubator/Keyframes#89]
I've been trying to run the script with CS6 with no luck, I wonder if it is not supported by CS6, otherwise if it does work if CS6 I'll continue searching for a solution.

**Comment by subtleGradient** [comment]
I haven't tried using it on CS6. I don't have any way to test it on CS6 right now.

Go ahead and install ExtendScript Toolkit and try running it from there. Change the one line `$.level = 0` to `$.level = 1` to get better error messages.

Try again with the new changes coming soon, it'll have better error handling.

**Comment by yozef** [comment]
thanks @subtleGradient. Here is that I've tried:
1- Copy/Pasted the files from [/Keyframes/tree/master/scripts](https://github.com/facebookincubator/Keyframes/tree/master/scripts) into: `/Applications/Adobe After Effects CS6/Scripts/Keyframes`:
![2017-01-11 at 11 38 15 am](https://cloud.githubusercontent.com/assets/287256/21857243/c6ee9dea-d7f2-11e6-8b19-06b8ec1753cd.png)

2- Copy pasted the code inside [/master/scripts/Keyframes_Exporter.jsx](https://github.com/facebookincubator/Keyframes/blob/master/scripts/Keyframes_Exporter.jsx) into ExtendScript Toolkit. Saved the file in `/Applications/Adobe After Effects CS6/Scripts/Keyframes.jsx`

3- I run the code from ES Toolkit:
![2017-01-11 at 11 38 17 am](https://cloud.githubusercontent.com/assets/287256/21857323/0491f91c-d7f3-11e6-99f3-7eb5f0dbf799.png)

4- In JS Console of ES Toolkit, I get: Result: undefined

5- I opened Adobe After Effects CS6, draw a square then do a simple transform, then this stays displayed. 
<img width="415" alt="2017-01-11 at 11 48 31 am" src="https://cloud.githubusercontent.com/assets/287256/21857602/ff511928-d7f3-11e6-9543-9108b9600c6d.png">

Is there anywhere else where the console displays more details?

**Comment by yozef** [comment]
Update: Did the steps above, however, I saved a copy of the .aep file on my desktop.

At Step 4 above, I see this:
<img width="414" alt="2017-01-11 at 11 54 09 am" src="https://cloud.githubusercontent.com/assets/287256/21857847/e8efcc64-d7f4-11e6-83d7-4353f1f00c6a.png">

In the newly created .log file on my desktop, it's empty.

**Comment by subtleGradient** [comment]
Try the latest version here: https://github.com/facebookincubator/Keyframes/releases/tag/previewer-v1
It fixes a bunch of little bugs and has better error handling. It also includes a Previewer for Android.

**Comment by yozef** [comment]
Worked!

Thanks 👍

**Comment by subtleGradient** [comment]
Sweet!

**Comment by subtleGradient** [comment]
Changes landed in master now
