### ISSUE TITLE
Unable to execute script at line 87

### ISSUE THREAD

**Issue by leeyc09** [facebookincubator/Keyframes#93]
can not execute script at AE cc 2015, 2017 , windows 10.

Error Message is 
"Can not run script at 87 line. Uncaught JavaScipt exception:TypeError:
cannot convert to c:\Programs files\adobe\~\Support File\script\~~~\AECompToKeyFramesAnimation.js"

**Comment by leeyc09** [comment]
error occur this function
`AECompToKeyFramesAnimation.js`
`function warnIfUsingMissingFeature(shouldWarn,feature)`

**Comment by leeyc09** [comment]
remove these line :
keyPath.unshift(comp&&comp.parentFolder$name);
console.warn('UNSUPPORTED: %s',keyPath.join(' → '));

you will work fine..

**Comment by subtleGradient** [comment]
Sorry for all the instability until now.
Try the latest version here: https://github.com/facebookincubator/Keyframes/releases/tag/previewer-v1
It fixes a bunch of little bugs and has better error handling. It also includes a Previewer for Android.

Let me know if this still gives you any problems.

**Comment by subtleGradient** [comment]
Changes landed in master now

**Comment by kongnanlive** [comment]
can not execute script at AE cc 2015 13.2, 2017 14.0, windows 7. Not all!

**Comment by kongnanlive** [comment]
@subtleGradient remove keyPath.unshift(comp&&comp.parentFolder$name);
console.warn('UNSUPPORTED: %s',keyPath.join(' → ')); Can work！
