### ISSUE TITLE
Clarification on the the exported JSON keys

### ISSUE THREAD

**Issue by fandy** [facebookincubator/Keyframes#98]
It would be useful to add some comments on a sample exported JSON in the docs. I was confused as to what `animation_frame_count`/ `animation_groups` meant.

**Comment by lozzle** [comment]
This is good feedback!  We're slowly putting together a site with more detailed documentation as well, and will keep this in mind!  https://facebookincubator.github.io/Keyframes/

**Comment by fandy** [comment]
Awesome, great job on this!
